login:
    path:      /login
    defaults:  { _controller: controllers.security:loginAction }

login_check:
    path:      /login_check

logout:
    path:      /logout

list_my_projects:
    path:      /
    defaults:  { _controller: controllers.list_my_projects:listAction }
    requirements:
        _method: GET

create_project:
    path:      /
    defaults:  { _controller: controllers.create_project:createAction }
    requirements:
        _method: POST
